<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/TestBlock.glb
-->
<script lang="ts">
	import {Group, Quaternion, Vector3} from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
	import {interactivity, useGltf} from '@threlte/extras'
    import {Collider, RigidBody} from "@threlte/rapier";
    import {base} from "$app/paths";
	import {type blockConfig} from "$lib/index";
	import { RigidBody as RapierRigidBody } from '@dimforge/rapier3d-compat'

    export let config: blockConfig;
    export const ref = new Group()

    export let rigidRef: RapierRigidBody

    const gltf = useGltf(`${base}/TestBlock.glb`)
    const component = forwardEventHandlers()

    interactivity()

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} >

    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <RigidBody  linearDamping={6} angularDamping={3} bind:rigidBody={rigidRef}>
            <Collider shape="cuboid" args={[0.38, 1.27, 0.38]} friction={0.1}/>
            <Collider shape="cuboid" args={[1.27, 0.38, 0.38]} friction={0.1}/>
            <Collider shape="cuboid" args={[0.38, 0.38, 1.27]} friction={0.1}/>
            <T.Mesh geometry={gltf.nodes.connector.geometry} scale={10}>
                <T.MeshStandardMaterial
                        color={config.color}
                        roughness={config.roughness}
                        metalness={config.metalness}
                />
            </T.Mesh>
        </RigidBody>

    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
